# Setup
Description


In [35]:
import numpy as np

arr = np.array([1,2,3])
arr = arr * 2

arr

array([2, 4, 6])

In [36]:
arr

array([2, 4, 6])

# Github Retrival

In [37]:
arr = arr * 2

arr

array([ 4,  8, 12])

In [38]:
arr = arr[-3:]

arr

array([ 4,  8, 12])

In [39]:
import pandas as pd

df = pd.DataFrame({'num_legs': [2, 4, 8, 0],
                    'num_wings': [2, 0, 0, 0],
                'num_specimen_seen': [10, 2, 1, 8]},
               index=['falcon', 'dog', 'spider', 'fish'])

df

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8

In [40]:


df

num_legs  num_wings  num_specimen_seen
falcon         2          2                 10
dog            4          0                  2
spider         8          0                  1
fish           0          0                  8